{
 "title": "Triton Inference Server",
 "description": "Nvidia Triton inference server metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Cumulative Inference Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "nv_inference_request_success", "legendFormat": "Success {{instance}}" },
    { "expr": "nv_inference_request_failure", "legendFormat": "Failure {{instance}}" }
   ]
  },
  {
   "title": "Load Ratio  (Total Time / Compute Time)",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(nv_inference_load_ratio_bucket[1m])) by (le)"
    }
   ]
  },
  {
   "title": "Queue Time (milliseconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(nv_inference_queue_duration_us[30s]) / 1000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Compute Time (milliseconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(nv_inference_compute_duration_us[30s]) / 1000",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}